version: "3.8"

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env.example
  #   environment:
  #     - APP_ENV=development
  #     - REDIS_HOST=localhost
  #     - REDIS_PORT=6379
  #     - REDIS_USERNAME=default
  #     - REDIS_PASSWORD=secret
  #     - REDIS_USE_TLS=false
  #     - PORT=8080
  #   depends_on:
  #     - redis
  #   ports:
  #     - "8080:8080"

  redis:
    image: redis:7.2-alpine
    command: ["redis-server", "--requirepass", "secret"]
    ports:
      - "6379:6379"
    environment:
      - REDIS_USERNAME=default
      - REDIS_PASSWORD=secret
